### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by bob0bob** [DarkRoleplay/Dark-Roleplay-Medieval#10]
I'm sorry to put this here.  I been searching all other the internet for information how to mine Salpeter Ore.   Unless it is a bug.  I've tried   stone pick axe and iron pick axe.   I can't find any information what is need.  Or if this is a bug that nothing falls when mining this material.

**Comment by JTK222** [comment]
It is a bug. Thanks ^^
I had it already fixed, but forgot to release it xD
Should be online on curse in about an hour, (probably in 10 or less minutes :P)
When you want faster answers feel free to join our discord: discord.dark-roleplay.net ^^
