### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Parahacker** [DarkRoleplay/Dark-Roleplay-Medieval#11]
There are a ton of items/blocks that have equivalents in other mods. Dark Roleplay does things differently, no question, but compatibility and avoiding duplication is still a big help for players.

What I've seen so far:
Tin ore (almost every tech mod and a few magic mods add this)
Food:
Wheat flour/dough (Harvestcraft, Natura, Forestry, Applied Energistics/Llamagistics...)
Barley (Natura, others)
Blueberries (so many mods - not that I blame them, blueberries are awesome)
Beetroot (Minecraft vanilla? I haven't been able to use this in DRM, so I'm not sure it's a dup)

If this is a topic that interests you, then let me know and I'll report other duplications I find. There were more I haven't mentioned already, I just don't want to overload the topic if you have reason to not pursue this.

**Comment by JTK222** [comment]
Hm... not sure about it...
Tin won't be remove able trough my ore system will be unique... (it's in the works atm)
Also the plants will work different than vanilla and other mods ones.
And the "Beetroot" is not a Beetroot :P It's a turnip, and you can expect more of such stuff as  beets were the main food in the Middleage (for example the equivalent to potatos were the "butterbeet" (can't find it's official translation)

In generall adding the ability to disable items is very problematic. First of server and client synch.
And worlds might also get corrupted by this.
Though... maybe with 1.13 when the world corruption issues are gone.

**Comment by JTK222** [comment]
There is a PR adding such a System to Forge, I will add support for that once it's accepted.
But it will just be a config option as Ores will work a bit different in the mod.
Crops will stay as they are in, and more will be added. The first one of them does now use the planned System (Barley) feel free to test it.

And I've overread something last time, if you have more things that you think are dupes just let me know, a few things might be changed.
Going to close this issue in ~72 hours if nobody answers as it's less a real issue then a quality of life thing.
