### ISSUE TITLE
Server Side Crash - MC 1.12.2 - Forge 93 (Attempting to load client sub-routine serverside)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [DarkRoleplay/Dark-Roleplay-Medieval#12]
https://gist.github.com/P3rf3ctXZer0/314b8dce6f56010662008536e256219a

**Comment by P3rf3ctXZer0** [comment]
isn't that the same crash you expirenced @Wyn-Price

**Comment by Wyn-Price** [comment]
yes. Ill make a fork now and fix it for this mod owner

**Comment by Wyn-Price** [comment]
This is actually really weird. Are you sure the crash occurs every time; and you have the latest version as there isnt a GUI screen being called at all

**Comment by P3rf3ctXZer0** [comment]
Yes.

**Comment by Wyn-Price** [comment]
Ok im downloading the source for the mod and im gonna do a bit of poking around. It should be fixed in around 10-20 minutes and Ill be able to privatly supply you with a .jar; as it looks like the original creator of this mod has left it months ago

**Comment by P3rf3ctXZer0** [comment]
I think he uploaded the wrong Jar to curse. I have seen that happen a few times.

**Comment by Wyn-Price** [comment]
ok ive set it all up im looking for an issue now

**Comment by Wyn-Price** [comment]
i cant actually see an issue with it at all it should work

**Comment by Wyn-Price** [comment]
and through testing it does work; HOWEVER I cant share a file with you. I hope you understand but the mod owner explicitly put [this](https://github.com/DarkRoleplay/Dark-Roleplay-Medieval/blob/master/src/main/resources/Ownership.info) in his files so Im gonna do the better thing and not share. Ill keep looking through the code and if i see anything wrong Ill fork it and send a pull request

**Comment by P3rf3ctXZer0** [comment]
lol I understand.

**Comment by JTK222** [comment]
Meh.. nope, my error... forgot to change one line in here... sorry... fix will be up soon.
Thanks for trying to find the bug Wyn-Price ^^

(Actually It was a W.i.P. feature I forgot to bring back to normal before releasing... I should really start to have 2 seperate brenches for w.i.p stuff and working stuff...)

**Comment by P3rf3ctXZer0** [comment]
Ready to test @JTK222 thanks for the quick response ^_^

**Comment by Wyn-Price** [comment]
Where was the error, as GUIScreen wasnt called at all in DRPMedievalBlocks.java or BarrelFilled.java

**Comment by JTK222** [comment]
The line was Cauldron :P As stated above didn't pushed the code yet. Gonna do that fast.

**Comment by Wyn-Price** [comment]
While searching for it i think i found a potentional crash at ItemTooltip.java. You're importing net.minecraft.client.gui.GuiScreen but regestering the class through a common directory, meaning that that class will try to run on a server and inevitably crash it. You should either register it through only the client or change every GuiScreen to net.minecraft.client.gui.GuiScreen

**Comment by JTK222** [comment]
Latest commits are up,
file should be available here: https://minecraft.curseforge.com/projects/dark-roleplay-medieval/files/2485534
The import isn't an issue at all. The compiler replaces GuiScreen with net.minecraft.client.gui.GuiScreen automaticly. Only the code shouldn't be callable.
At least I haven't gotten any crash/bug reports due to this :P 
Though gonna change that, just to be sure, thank you ^^

**Comment by Wyn-Price** [comment]
@P3rf3ctXZer0  the file wont be ready for about 5 minutes. It has to go through checks and moderation

**Comment by JTK222** [comment]
It's under review for 10 minutes now :P Usually I've got the luck and when I make a fast bugfix they let it trough in around 1 minute ^^

**Comment by JTK222** [comment]
ok... just gonna go off for today... you know what to do when it still won't work when curse finally accepts this file D: (30 minutes now never had to wait so long D:)

**Comment by P3rf3ctXZer0** [comment]
@JTK https://gist.github.com/P3rf3ctXZer0/d149471a1dea781a03e8ccdf9ec830e2

**Comment by Wyn-Price** [comment]
I cant help, as the github isnt updated to what the source code is

**Comment by JTK222** [comment]
Beside the fact that I've updated the code yesterday (and have even written it here :P)
try that: http://dark-roleplay.net/secret/Dark%20Roleplay%20Medieval-0.2.2.1b.jar

**Comment by JTK222** [comment]
Ok, all issues are fixed somebody else tested it. Latest versions are on curse. Thanks for the reports!
