### ISSUE TITLE
crash client

### ISSUE THREAD

**Issue by demon57730** [DarkRoleplay/Dark-Roleplay-Medieval#13]
crash client forge 1.12.2
Dark+Roleplay+Medieval+Alpha-0.2.4c
Dark+Roleplay+Core+Alpha-0.3.5e

log

https://pastebin.com/M3Li5DtM

**Comment by JTK222** [comment]
Hm... I hoped that I've got fixed that already :/
Will need a way to block such blocks from the placement preview.
Would suggest you to disable the placement preview in the configs till then. 
(or try to avoid blocks from mods using codechicken lib)

**Comment by demon57730** [comment]
or suprime your mod no the will not disable the other mod after say disable in the config I will not tell all the player will disable in your config

so I delete your mod

**Comment by JTK222** [comment]
Will be fixed with DRPCore v0.3.6
