### ISSUE TITLE
Crash w/ Candy World Mod

### ISSUE THREAD

**Issue by WenXin20** [DarkRoleplay/Dark-Roleplay-Medieval#17]
Forge 14.23.4.2772-1.12.2
Dark Roleplay Core v0.4.6.2
Dark Roleplay Medieval v0.2.8-pre2
[Candy World](https://minecraft.curseforge.com/projects/candy-world) v1.1.2

I received this crash while loading the game with the Candy mod.
[Crash Report](https://gist.github.com/WenXin20/5ef99aaf91cb7539cd27cbeec3de0033)

**Comment by JTK222** [comment]
The only mod adding support for MaARG and of course the file is wrong xD
(That's my fault! I changed some things thinking that no one supports it yet)
Going to PR a fix for this to Candy World after school.
Till then you can delete following folder within candy world:
/data/candymod/arg/ (everything within that folder)

**Comment by JTK222** [comment]
https://github.com/ochotonida/candymod/pull/27 fixes this.
Going to close this issue as soon as the Pull Request is accepted.

**Comment by JTK222** [comment]
Fixed! https://minecraft.curseforge.com/projects/candy-world/files/2642499
