### ISSUE TITLE
Adding JEI integration

### ISSUE THREAD

**Issue by Tschipp** [DarkRoleplay/Dark-Roleplay-Medieval#26]
I think it would be so nice to have JEI integration for all custom recipes, it's so hard to figure out how to craft everything. If you want, and maybe if I have time, I could do a PR for it.

**Comment by JTK222** [comment]
I had it in the past. JEI has changed it's API 2 times in that time..
Not going to re-implement for the current crafting system therefore.
Also, the 1.12 version for this mod is dead from my point of view.
Not going to do anything else than bugfixes (eventually minor changes, like the chairs thing).

(The 1.14 version will have a new crafting system btw)

However... if you really want that feature, here is the a link to the old implementation I had.
https://github.com/DarkRoleplay/Dark-Roleplay-Core/tree/master/src/main/java/net/dark_roleplay/drpcore/addons/jei
Feel free to turn it into a small addon.

**Comment by Tschipp** [comment]
Thanks for the response. When you mean addon, you probably mean a separate addon mod, as in you won't accept any new PR's for the 1.12.2 version?

**Comment by Tschipp** [comment]
![image](https://user-images.githubusercontent.com/11649893/64613396-512ee280-d3d6-11e9-81b7-cfeaac7359d1.png)
I've forked DRPCore and added it, didn't take too long. Will make a PR there.
