### ISSUE TITLE
[1.14.4] Fails to load

### ISSUE THREAD

**Issue by WenXin20** [DarkRoleplay/Dark-Roleplay-Medieval#27]
`Minecraft v1.14.4`
`Forge v28.1.109`
`DRP Medieval v0.4.1`

This occurred on game load.
[Log](https://gist.github.com/WenXin20/e72f570cefa723cfee6ad015cd40748b)
![2020-01-07_19 38 59](https://user-images.githubusercontent.com/12000593/71943246-9943f300-3185-11ea-9a28-06b90a918752.png)

**Comment by JTK222** [comment]
To be fair curse killed the additional file for the second version
and it wasn't obvious enough for people that already know the mod.
So I changed the description on the project page.
![image](https://user-images.githubusercontent.com/10399186/71966022-25dfc700-3201-11ea-995e-400bc607baaf.png)
Here's the link for the MARG file https://www.curseforge.com/minecraft/mc-mods/dark-roleplay-medieval/files/2854155
It's a seperate mod, that was packaged into the Medieval mod in 1.12 but that system wasn't updated yet, so till then you need to download that mod seperatly.
It'll get it's own mod page once it's stable enough.

**Comment by WenXin20** [comment]
Alright, thanks!
