### ISSUE TITLE
DRP AttachCapabilityTileEntity crashes EnderIO - Forestry interaction 

### ISSUE THREAD

**Issue by enricotagliavini** [DarkRoleplay/Dark-Roleplay-Medieval#3]
This is very easy to reproduce. Take an EIO Stirling generator place on one side a capacitor bank and connect the two with energy conduit, also add an additional energy conduit to the other side of the capacitor bank for a forestry's carpenter. Put fuel (coal) into the generator to have power. Now place the carpenter next to the capacitor bank. As soon as the carpenter is placed the world crashes with the following crash report.

[crash-2017-01-14_23.34.04-server.txt](https://github.com/DarkRoleplay/Dark-Roleplay-Medieval/files/706256/crash-2017-01-14_23.34.04-server.txt)

The world crashes upon load if this is a server. When using a local game the world is not saved, hence you are able to login as the carpenter is not there.

Removing DRP and leaving everything as it is fixes the problem, hence I guess it's a DRP issue.

Screenshot of the setup (taken while DRP was removed):
![enderio-forestry-setup](https://cloud.githubusercontent.com/assets/8146008/21958652/6b6e61bc-dab3-11e6-8cbd-acf80250764e.png)

DRP version: 0.1.6

**Comment by JTK222** [comment]
Thx found the Issue will hopefully be fixed with the next (and hopefully soon released) version.

**Comment by enricotagliavini** [comment]
Great news, thank you!

**Comment by JTK222** [comment]
Ok, sorry. Looks like eclipse hasn't saved this properly.
This time it will be fixed by 100% D:

**Comment by thiakil** [comment]
Was this released properly? It has come up again https://github.com/aidancbrady/Mekanism/issues/4440

**Comment by JTK222** [comment]
Yeah it was, that guy just used an old version. They've already noticed it in the report. But still thanks ^^

**Comment by thiakil** [comment]
Apologies for necro posting then, I'd assumed by now they'd be using the latest version and didnt have time to check!

**Comment by JTK222** [comment]
Nothing to apologize xD People will never use the latest version, that just something like asking them to stop breathing :P Same goes for telling them to make backups before updating xD
