### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [DarkRoleplay/Dark-Roleplay-Medieval#33]
`Minecraft v1.16.5`
`Forge v36.1.24`
`Project Brazier v0.5.2`
[`Quark r2.4-312`](https://www.curseforge.com/minecraft/mc-mods/quark)
[`Quark Oddities v1.16.3`](https://www.curseforge.com/minecraft/mc-mods/quark-oddities)
[`Mystical World v0.3.1.10`](https://www.curseforge.com/minecraft/mc-mods/mystical-world)

My server crashes during load, Quark Oddities and Mystical World may be involved according to the crash report. Neither mod crashes until Project Brazier is added.
[Crash Report](https://gist.github.com/WenXin20/142061cfe962a61d8c72560c7d8c70a4)
[Server Log](https://gist.github.com/WenXin20/c20bbaf1acfb882ed901b3a1441ec397#file-latest-log-L3094)

**Comment by JTK222** [comment]
Now properly fixed with this https://github.com/DarkRoleplay/Project-Brazier/commit/910338eb12baa3089726eca607205c0a4b4e0d05
