### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by yepidoodles** [DarkRoleplay/Dark-Roleplay-Medieval#4]
http://www.codesend.com/view/5a40de4e6979419ce592eb6400bf7bf3/

**Comment by JTK222** [comment]
Changelog
* Done some things but forget what exactly :O 
new DRP Medieval won't work with older versions.

Update the Core mod and it will work:
https://minecraft.curseforge.com/projects/dark-roleplay-core/files/2352028

**Comment by yepidoodles** [comment]
I used the latest 1.10.2 version

**Comment by JTK222** [comment]
Hm.. .strange the log said you are using core mod version 0.1.6 instead of 0.1.7.
Might be a fail on my side wont be able to test it before next monday.
