### ISSUE TITLE
1.11.2 Crash - DRM 0.1.8

### ISSUE THREAD

**Issue by sdaddy** [DarkRoleplay/Dark-Roleplay-Medieval#7]
I thought the crash was with the Extra Rails mod, but that mod developer says it's DRM.

Crash log and mod developer's comments can be found here: https://github.com/shadowfacts/ExtraRails/issues/5#event-1043759702

**Comment by JTK222** [comment]
That's already fixed but not released yet. Still not understanding why this is even possible...
Little description for everybody that is interested in the matter:
Forge triggers the event to attach a capability to a Tile Entity sometimes before the tile entity has been created.

**Comment by sdaddy** [comment]
Do you have any ETA on the release with this fix? Would love to include the mod in my pack. Thanks.

**Comment by JTK222** [comment]
Generally no, but one of my "Beta" testers got already a version. I will ask him today if he had any other major bugs. If he hadn't had any I will release the version today/tomorrow (depending on your timezone :P)
But it will be version 0.1.8.5 as it's missing features to be 0.1.9 and got too many to become 0.1.8b D:

**Comment by JTK222** [comment]
Here is the link to the file: https://minecraft.curseforge.com/projects/dark-roleplay-medieval/files/2408890
